name: Add to obs-docs project
on:
  issues:
    types:
      - labeled
permissions:
  contents: read

jobs:
  add_to_project:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'Team:Docs'
    steps:
      - name: Get token
        id: get_token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.OBS_AUTOMATION_APP_ID }}
          private-key: ${{ secrets.OBS_AUTOMATION_APP_PEM }}
          permission-organization-projects: write
          permission-issues: read
      - uses: octokit/graphql-action@ddde8ebb2493e79f390e6449c725c21663a67505 # v2.x
        id: add_to_project
        with:
          query: |
            mutation add_to_project($projectid:ID!,$contentid:ID!) {
              addProjectV2ItemById(input:{projectId:$projectid contentId:$contentid}) {
                item {
                  ... on ProjectV2Item {
                    id
                  }
                }
              }
            }
          projectid: ${{ env.PROJECT_ID }}
          contentid: ${{ github.event.issue.node_id }}
        env:
          PROJECT_ID: "PVT_kwDOAGc3Zs0iZw"
          GITHUB_TOKEN: ${{ steps.get_token.outputs.token }}
