name: smoke-tests
run-name: Smoke Tests

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 1-5'

# Limit the access of the generated GITHUB_TOKEN
permissions:
  contents: read

jobs:
  prepare-smoke-tests-os:
    name: Generate smoke tests list
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - id: generate
        name: Generate matrix
        uses: elastic/apm-pipeline-library/.github/actions/elastic-stack-snapshot-branches@feature/exclude-branches
        with:
          exclude-branches: '7.17'

  smoke-tests-os:
    name: Run smoke tests OS
    needs: prepare-smoke-tests-os
    strategy:
      matrix: ${{ fromJSON(needs.prepare-smoke-tests-os.outputs.matrix) }}
    uses: ./.github/workflows/smoke-tests-os.yml
    with:
      branch: ${{ matrix.branch }}
    secrets: inherit

  smoke-tests-ess:
    name: Run smoke tests ESS
    uses: ./.github/workflows/smoke-tests-ess.yml
    with:
      branch: 'main'
    secrets: inherit
