name: smoke-tests
run-name: Smoke Tests

on:
  workflow_dispatch: ~
  schedule:
    - cron: '0 3 * * 1-5'

# Limit the access of the generated GITHUB_TOKEN
permissions:
  contents: read

jobs:
  prepare-smoke-tests-os:
    name: Generate smoke tests list
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: generate
        name: Generate matrix
        uses: elastic/oblt-actions/elastic/active-branches@v1
        with:
          exclude-branches: '7.17'

  smoke-tests-os:
    name: Run smoke tests OS
    needs: prepare-smoke-tests-os
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.prepare-smoke-tests-os.outputs.matrix) }}
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/smoke-tests-os.yml
    with:
      branch: ${{ matrix.branch }}
    secrets: inherit

  smoke-tests-ess:
    name: Run smoke tests ESS
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/smoke-tests-ess.yml
    with:
      branch: 'main'
    secrets: inherit

  all-smoke-tests:
    name: All Smoke Tests
    if: always()
    runs-on: ubuntu-latest
    needs:
      - smoke-tests-os
      - smoke-tests-ess
    steps:
      - id: check
        uses: elastic/oblt-actions/check-dependent-jobs@v1
        with:
          jobs: ${{ toJSON(needs) }}
          skipped-as-success: 'true'
      - uses: elastic/oblt-actions/slack/notify-result@v1
        with:
          bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel-id: "#apm-server"
          status: ${{ steps.check.outputs.status }}
