---
# Dependabot Pull Requests are not updating the NOTICE.txt file, which causes the lint job to fail.
# This workflow will checkout the dependabot PR, update the NOTICE.txt file, and push the changes back to the PR.
name: update-dependabot-pr

on:
  push:
    branches:
      - dependabot/go_modules/**
    paths-ignore:
      - NOTICE.txt
      - NOTICE-fips.txt

permissions:
  contents: read

jobs:
  update-dependabot-pr:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        id: get_token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.OBS_AUTOMATION_APP_ID }}
          private-key: ${{ secrets.OBS_AUTOMATION_APP_PEM }}
          permission-contents: write

      - uses: actions/checkout@v6
        with:
          token: ${{ steps.get_token.outputs.token }}

      - name: Configure git user
        uses: elastic/oblt-actions/git/setup@v1
        with:
          github-token: ${{ steps.get_token.outputs.token }}

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@e89d40939c28e39f97cf32126055eeae86ba74ec  # v6.3.0
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: false

      - name: Update NOTICE.txt
        run: make notice

      - name: Debug diff
        run: git status --porcelain

      - name: Check if NOTICE.txt has changed
        id: check-notice-diff
        run: |
          if git status --porcelain | grep -q 'NOTICE.txt\|NOTICE-fips.txt'; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          else
            echo "changed=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Debug output
        run: |-
          echo 'changed: ${{ steps.check-notice-diff.outputs.changed }}'

      - name: Commit changes (signed)
        if: ${{ steps.check-notice-diff.outputs.changed == 'true' }}
        run: |
          git add NOTICE.txt NOTICE-fips.txt
          git commit -m "Update NOTICE.txt and NOTICE-fips.txt"
          git push
